// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsLocalStorageApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsLocalStorageApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsLocalStorageApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashLocalStorageApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashLocalStorageApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashLocalStorageApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct FavoriteProduct: Hashable {
  var id: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FavoriteProduct? {
    let id = pigeonVar_list[0] as! String

    return FavoriteProduct(
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      id
    ]
  }
  static func == (lhs: FavoriteProduct, rhs: FavoriteProduct) -> Bool {
    return deepEqualsLocalStorageApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashLocalStorageApi(value: toList(), hasher: &hasher)
  }
}

private class LocalStorageApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return FavoriteProduct.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LocalStorageApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FavoriteProduct {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LocalStorageApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LocalStorageApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LocalStorageApiPigeonCodecWriter(data: data)
  }
}

class LocalStorageApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LocalStorageApiPigeonCodec(readerWriter: LocalStorageApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LocalStorageApi {
  func addFavorite(id: String) throws
  func getFavorites() throws -> [FavoriteProduct]
  func isFavorite(id: String) throws -> Bool
  func removeFavorite(id: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LocalStorageApiSetup {
  static var codec: FlutterStandardMessageCodec { LocalStorageApiPigeonCodec.shared }
  /// Sets up an instance of `LocalStorageApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LocalStorageApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let addFavoriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.candy_store.LocalStorageApi.addFavorite\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addFavoriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.addFavorite(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addFavoriteChannel.setMessageHandler(nil)
    }
    let getFavoritesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.candy_store.LocalStorageApi.getFavorites\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFavoritesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFavorites()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFavoritesChannel.setMessageHandler(nil)
    }
    let isFavoriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.candy_store.LocalStorageApi.isFavorite\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isFavoriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          let result = try api.isFavorite(id: idArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isFavoriteChannel.setMessageHandler(nil)
    }
    let removeFavoriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.candy_store.LocalStorageApi.removeFavorite\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeFavoriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.removeFavorite(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeFavoriteChannel.setMessageHandler(nil)
    }
  }
}
